### ISSUE TITLE
Desktop Build using Electron 

### ISSUE THREAD

**Issue by MichaelFay** [Musish/Musish#367] opened 2019-04-21 17:09 UTC
**Is your feature request related to a problem? Please describe.**
It would be very nice if this could be wrapped in something like electron js so it could be used as a standalone desktop application. 

**Describe the solution you'd like**
Use electron js to build a desktop variant of this application.

**Comment by BrychanOdlum** [comment] 2019-04-26 07:06
Duplicate of #238 

(TLDR: having issues authenticating with Apple, currently not possible (at least not by any method I've found)

**Closed by BrychanOdlum** 2019-04-26 07:06 UTC
Labels: enhancement
