### ISSUE TITLE
BUG: All user library playlists aren't available in the sidebar

### ISSUE THREAD

**Issue by owellsjr** [Musish/Musish#219] opened 2019-01-21 17:48 UTC
**Describe the bug**
The sidebar only displays a user's first 25 playlists. 

**To Reproduce**
1. Go to https://musi.sh
2. Login
3. Scroll down to 'Playlists' in the sidebar

**Expected behavior**
All playlists in the user library should be accessible in the sidebar.

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.3 Beta (18D39a)
 - Browser: Safari
 - Version: 12.0.3

**Comment by raphaelvigee** [comment] 2019-01-23 03:31
Duplicate of #202

**Closed by raphaelvigee** 2019-01-23 03:31 UTC
Labels: bug
