### ISSUE TITLE
BUG: Explicit Songs not playing

### ISSUE THREAD

**Issue by Rusew0** [Musish/Musish#257] opened 2019-01-24 18:53 UTC
**Describe the bug**
I can't listen to Explicit music. 
**To Reproduce**
1. Go to 'https://musi.sh/'
2. Click on Any explicit song

**Screenshots**
![default](https://user-images.githubusercontent.com/47008348/51701227-6f53f800-202a-11e9-899b-8641d279c623.jpg)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]
 - Version [e.g. 71.0.3578.98]

**Additional context**
I enable expicit content in Itunes and apple music on my device.

**Comment by jamesjarvis** [comment] 2019-01-24 19:18
Duplicate of #218

**Closed** 2019-01-24 19:19 UTC
Labels: bug, duplicate
