### ISSUE TITLE
BUG: Can't play explicit songs

### ISSUE THREAD

**Issue by yashptel** [Musish/Musish#372] opened 2019-04-28 20:07 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by BrychanOdlum** [comment] 2019-04-29 16:34
Duplicate of #218

**Closed by BrychanOdlum** 2019-04-29 16:34 UTC
Labels: bug
