### ISSUE TITLE
FEATURE - Dark Mode

### ISSUE THREAD

**Issue by mviscito** [Musish/Musish#375] opened 2019-05-02 10:44 UTC
Hi I think Musi.sh is amazing as it allows me to stream Apple Music to Google Home using Chrome, however I what would make it even more awesome is a dark mode.

**Comment by jamesjarvis** [comment] 2019-05-03 20:33
Great suggestion! Unfortunately a duplicate of #206

**Closed by jamesjarvis** 2019-05-03 20:33 UTC
Labels: enhancement
