### ISSUE TITLE
FEATURE: Remove Pause Between Track Changes in Albums

### ISSUE THREAD

**Issue by peachtart** [Musish/Musish#330] opened 2019-03-21 01:16 UTC
Currently there is a moment of silence during track changes in albums while the next song is being fetched, which for tracks that are intended to run seamlessly into each other is disruptive when listening.

Presumably the pause is due to the next song being fetched via the API, would it be possible to prefetch the song and have it play seamlessly?

**Comment by BrychanOdlum** [comment] 2019-04-26 17:42
Duplicate of #241, closing.

**Closed by BrychanOdlum** 2019-04-26 17:42 UTC
Labels: enhancement
