### ISSUE TITLE
BUG:im only allowed to listen the first 70 songs on a playlist

### ISSUE THREAD

**Issue by mmejia150** [Musish/Musish#447] opened 2019-08-29 17:34 UTC
**Describe the bug**
im only allowed to listen the first 70 songs on a playlist
*To Reproduce**

1. Go to 'any playlist with 179 songs'
2. Click on 'shuffle'
3. Scroll down to 'up next'

**Expected behavior**
it'll only shuffle the first 70 songs and let me play the first 70 songs
**Screenshots**

**Desktop (please complete the following information):**

- OS: chrome os
- Browser chrome
- Version 75.0.3770.144 (Official Build) (64-bit)

**Additional context**

**Comment by BrychanOdlum** [comment] 2019-09-04 01:52
Duplicate of #233

**Closed by BrychanOdlum** 2019-09-04 01:52 UTC
Labels: bug
